format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_usart}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_USART_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usart, value: Synchronous}
      - type: User
        attributes: {value: Synchronous}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_usart}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: DRV_USART_CLIENTS_NUM}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '2'}
      - type: Comment
        attributes: {id: DRV_USART_DEPENDENCY_DMA_COMMENT}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
      - type: String
        attributes: {id: DRV_USART_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_0, value: USART0}
      - type: Boolean
        attributes: {id: DRV_USART_RX_DMA}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: readOnly}
            children:
            - {type: Value, value: 'false'}
      - type: Integer
        attributes: {id: DRV_USART_RX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_0, value: '-1'}
      - type: Boolean
        attributes: {id: DRV_USART_TX_DMA}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: readOnly}
            children:
            - {type: Value, value: 'false'}
      - type: Integer
        attributes: {id: DRV_USART_TX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_0, value: '-1'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_usart_UART_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usart0}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: USART0_UART}
  - type: InstanceComponent
    attributes: {instance: '1', id: drv_usart}
    children:
    - type: Symbols
      children:
      - type: Comment
        attributes: {id: DRV_USART_DEPENDENCY_DMA_COMMENT}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
      - type: String
        attributes: {id: DRV_USART_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_1, value: USART1}
      - type: Integer
        attributes: {id: DRV_USART_QUEUE_SIZE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
      - type: Boolean
        attributes: {id: DRV_USART_RX_DMA}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: readOnly}
            children:
            - {type: Value, value: 'false'}
      - type: Integer
        attributes: {id: DRV_USART_RX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_1, value: '-1'}
      - type: Boolean
        attributes: {id: DRV_USART_TX_DMA}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: readOnly}
            children:
            - {type: Value, value: 'false'}
      - type: Integer
        attributes: {id: DRV_USART_TX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_1, value: '-1'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_usart_UART_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usart1}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: USART1_UART}
  - type: InstanceComponent
    attributes: {instance: '2', id: drv_usart}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_USART_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_2, value: USART2}
      - type: Integer
        attributes: {id: DRV_USART_QUEUE_SIZE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
      - type: Integer
        attributes: {id: DRV_USART_RX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_2, value: '-1'}
      - type: Integer
        attributes: {id: DRV_USART_TX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_2, value: '-1'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_usart_UART_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usart2}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: USART2_UART}
- type: ElementPosition
  attributes: {x: '229', y: '202', id: drv_usart}
