format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: FREERTOS_CPU_CLOCK_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '300000000'}
  - type: Integer
    attributes: {id: FREERTOS_MAX_TASK_NAME_LEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '16'}
  - type: Integer
    attributes: {id: FREERTOS_TICK_RATE_HZ}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1000'}
- type: ElementPosition
  attributes: {x: '48', y: '79', id: FreeRTOS}
